language: node_js
node_js:
  - "stable"
install:
  - npm install
script:
  - gulp dist
  - gulp critical
deploy:
  on: master
  skip_cleanup: true
  provider: surge
  project: dist/
  domain: themihel.me
