---
label: Project
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: textarea
  name: Description
  label: Description
- type: list
  name: Tags
  label: Tags
- type: file
  name: featureimage
  label: Feature - Image
- type: text
  name: FeatureImageDescription
  label: Feature - Image Description
- type: list
  name: Links
  label: Links
pages:
- content/project/test-project.md
